"""
RSJ-FFMPEG Utilities
Helper functions and utilities
"""

import os
import json
import hashlib
from pathlib import Path
from typing import Dict, Any, List
from datetime import datetime


def format_duration(seconds: float) -> str:
    """Format duration in seconds to HH:MM:SS"""
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    return f"{hours:02d}:{minutes:02d}:{secs:02d}"


def get_file_hash(filepath: str) -> str:
    """Calculate MD5 hash of file"""
    hash_md5 = hashlib.md5()
    with open(filepath, "rb") as f:
        for chunk in iter(lambda: f.read(4096), b""):
            hash_md5.update(chunk)
    return hash_md5.hexdigest()


def format_file_size(size_bytes: int) -> str:
    """Format file size in human-readable format"""
    for unit in ['B', 'KB', 'MB', 'GB', 'TB']:
        if size_bytes < 1024.0:
            return f"{size_bytes:.1f}{unit}"
        size_bytes /= 1024.0
    return f"{size_bytes:.1f}PB"


def generate_report(
    jobs: List[Dict[str, Any]],
    format: str = "json",
    output_file: str = "report"
) -> str:
    """
    Generate processing report
    
    Args:
        jobs: List of job results
        format: Report format (json, markdown)
        output_file: Output filename (without extension)
        
    Returns:
        Path to generated report
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    if format == "json":
        report = {
            "toolkit": "RSJ-FFMPEG",
            "version": "2.0.0",
            "timestamp": timestamp,
            "processed_by": "RAJSARASWATI JATAV",
            "jobs": jobs,
            "summary": {
                "total_jobs": len(jobs),
                "completed": sum(1 for j in jobs if j.get("status") == "completed"),
                "failed": sum(1 for j in jobs if j.get("status") == "failed")
            }
        }
        
        output_path = f"{output_file}.json"
        with open(output_path, 'w') as f:
            json.dump(report, f, indent=2)
        
        return output_path
    
    elif format == "markdown":
        md_content = f"""# RSJ-FFMPEG Processing Report

**Generated by:** RAJSARASWATI JATAV  
**Date:** {timestamp}  
**Toolkit Version:** 2.0.0

## Summary
- **Total Jobs:** {len(jobs)}
- **Completed:** {sum(1 for j in jobs if j.get("status") == "completed")}
- **Failed:** {sum(1 for j in jobs if j.get("status") == "failed")}

## Job Details

| ID | Input | Output | Status | Duration |
|----|-------|--------|--------|----------|
"""
        
        for i, job in enumerate(jobs, 1):
            status_icon = "✅" if job.get("status") == "completed" else "❌"
            md_content += f"| {i} | {job.get('input', 'N/A')} | {job.get('output', 'N/A')} | {status_icon} | {job.get('duration', 'N/A')} |\n"
        
        md_content += "\n---\n**© 2025 RAJSARASWATI JATAV | All Rights Reserved**\n"
        
        output_path = f"{output_file}.md"
        with open(output_path, 'w') as f:
            f.write(md_content)
        
        return output_path
    
    return ""


def validate_ffmpeg() -> bool:
    """Check if FFmpeg is installed"""
    import subprocess
    try:
        subprocess.run(["ffmpeg", "-version"], capture_output=True, check=True)
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False


def validate_ffprobe() -> bool:
    """Check if FFprobe is installed"""
    import subprocess
    try:
        subprocess.run(["ffprobe", "-version"], capture_output=True, check=True)
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False


def system_check() -> Dict[str, Any]:
    """Perform system check for required dependencies"""
    return {
        "ffmpeg": validate_ffmpeg(),
        "ffprobe": validate_ffprobe(),
        "python_version": __import__('sys').version,
        "platform": __import__('platform').system()
    }


def create_directory_structure(base_path: str):
    """Create standard directory structure for RSJ-FFMPEG"""
    directories = [
        "input",
        "output",
        "logs",
        "reports",
        "temp",
        "plugins",
        "templates"
    ]
    
    base = Path(base_path)
    for directory in directories:
        (base / directory).mkdir(parents=True, exist_ok=True)


def clean_temp_files(temp_dir: str = "temp"):
    """Clean temporary files"""
    temp_path = Path(temp_dir)
    if temp_path.exists():
        for file in temp_path.glob("*"):
            if file.is_file():
                file.unlink()


def load_config(config_path: str) -> Dict[str, Any]:
    """Load configuration from JSON file"""
    if os.path.exists(config_path):
        with open(config_path, 'r') as f:
            return json.load(f)
    return {}


def save_config(config: Dict[str, Any], config_path: str):
    """Save configuration to JSON file"""
    with open(config_path, 'w') as f:
        json.dump(config, f, indent=2)